# Schema for the configuration files of the Breadcrumb extra field module.

webform_extra_field.settings:
  type: config_object
  label: 'Webform extra field settings'
  mapping:
    webform_extra_field_admin:
      type: sequence
      label: 'Entities'
      entity_type_bundles:
        type: sequence
        label: 'Entity type bundles'
        bundle:
          type: string
          label: 'Bundle'
