entity_field_token.field_token_display.*:
  type: config_entity
  label: 'Entity field token display'
  mapping:
    id:
      type: string
      label: 'Identifier'
    label:
      type: string
      label: 'Label'
    entity_type:
      type: string
      label: 'Entity type'
    bundles:
      type: sequence
      label: 'Entity bundles'
      sequence:
        type: string
        label: 'Entity bundle'
    view_modes:
      type: sequence
      label: 'Entity view modes'
      sequence:
        type: string
        label: 'Entity view mode'
    field_type:
      type: string
      label: 'Field type'
    field_value:
      type: entity_field_token.field_value.[%parent.field_type]

entity_field_token.field_value.textfield:
  type: string
  label: 'Field value'

entity_field_token.field_value.text_format:
  type: mapping
  label: 'Text format value'
  mapping:
    value:
      type: text
      label: 'Field value'
    format:
      type: string
      label: 'Field value format'
